name: Check Translation

on:
  pull_request:
    branches:
      - test-new-workflow
    paths:
      - 'en/**'
      - 'es/**'
      - 'fr/**'
      - 'it/**'
      - 'id/**'
      - 'ja/**'
      - 'ko/**'
      - 'pt-br/**'
      - 'ru/**'
      - 'sk/**'
      - 'th/**'
      - 'tr/**'
      - 'uk/**'
      - 'uz/**'
      - 'zh-cn/**'
      - 'zh-tw/**'
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'PR number to check'
        required: true

jobs:
  check-translation:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check modified files
        id: check_files
        uses: actions/github-script@v5
        with:
          script: |
            const core = require('@actions/core');
            const languages = ['en', 'es', 'fr', 'it', 'id', 'ja', 'ko', 'pt-br', 'ru', 'sk', 'th', 'tr', 'uk', 'uz', 'zh-cn', 'zh-tw'];
            const prNumber = context.eventName === 'workflow_dispatch' ? context.payload.inputs.prNumber : context.issue.number;
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const modifiedLanguages = new Set(files.map(file => file.filename.split('/')[0]));
            const labelsToAdd = languages.filter(lang => !modifiedLanguages.has(lang)).map(lang => `requires-translation-${lang}`);
            core.setOutput("labels_to_add", labelsToAdd.join(','));

      - name: Trigger Label Adding Workflow
        if: steps.check_files.outputs.labels_to_add != ''
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: add-labels
          client-payload: |
            {
              "pr_number": "${{ github.event.pull_request.number }}",
              "labels": "${{ steps.check_files.outputs.labels_to_add }}"
            }
